import { AppContainer, GlobalStyles } from "@/styles/GlobalStyles";
import StyledComponentsRegistry from "./StyledComponentsRegistry";
import type { Metadata } from "next";
import HeaderServer from "@/components/Header/HeaderServer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ru">
      <body>
        <StyledComponentsRegistry>
          <GlobalStyles />
          <AppContainer>
            <HeaderServer />
            {children}
          </AppContainer>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
