import Header from "@/components/Header/Header";
import { AppContainer, GlobalStyles } from "@/styles/GlobalStyles";
import { MenuItem } from "@/components/Header/types";
import type { Metadata } from "next";
import StyledComponentsRegistry from "./StyledComponentsRegistry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getMenuItems(): Promise<MenuItem[]> {
  const res = await fetch("http://127.0.0.1:8000/api/menuitem", {
    next: { revalidate: 60 * 60 }, // кэш на 1 час
  });

  if (!res.ok) {
    console.error("Failed to fetch menu, using fallback");
    return [];
  }

  return res.json();
}

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const menuItems = await getMenuItems();

  return (
    <html lang="ru">
      <body>
        <StyledComponentsRegistry>
          <GlobalStyles />
          <AppContainer>
            <Header menuItems={menuItems} />
            {children}
          </AppContainer>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
