version: "3.9"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next_client
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    # Убрать volume, чтобы не перезаписывать собранное приложение